name: Deploy Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  Build-deploy-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Inventory Image"
        run: |
          docker build -t ghcr.io/kunniii/python_telegram_bot:latest .
          docker push ghcr.io/kunniii/python_telegram_bot:latest
